name: elmasreenapp
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #swipppper
  flutter_swiper: ^1.1.6
  #verification code
  pin_code_fields: ^4.0.0
  #rating bar plugin
  flutter_rating_bar: ^3.0.1+1
  #share application on social media
  flutter_share: ^1.0.2+1
  ##doted border
  dotted_border: ^1.0.7
  font_awesome_flutter: ^8.11.0
  flutter_dash: ^0.0.1
  dotted_line: ^2.0.2
  #toast sms
  toast: ^0.1.5
  ##statemanagment
  provider: ^4.0.4
  #local database and path plugin
  sqflite: ^1.3.1
  google_maps_flutter: ^0.5.25+3
  ##loading
  flutter_spinkit: "^4.1.2"
  #sharedprefrence to save data
  shared_preferences: ^0.5.6+3
  #imagepicker
  image_picker: ^0.6.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  ##timelines:
  http: ^0.12.0
    ##get path file
  path: ^1.6.4
  ##medai type of image
  http_parser: ^3.1.4
  ##reading html divs
  flutter_html: ^0.11.0
    #open what is
 ## flutter_launch: ^0.1.2
  #url launcher
  url_launcher: ^5.5.2
  #firebase messaging
  firebase_messaging: ^6.0.13
  #notification local
  flutter_local_notifications: ^1.4.2
  hb_check_code: ^0.0.1
  random_string: ^2.1.0
  location: ^3.0.2


dev_dependencies:
   flutter_launcher_icons: "^0.7.3"
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: mainfont
      fonts:
         - asset: fonts/mainfont.ttf
           weight: 100
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
