class EN {
  static const Map<String, String> english = {
    'language_arabic': 'Arabic',
    'language_english': 'إنجليزي',
    'btn_skip': 'Skip',
    'second_title_intro':'من فضلك أنتظر تحميل التطبيق',
    'first_title_intro':'Please wait for  the application to loading',
    'btn_login': 'Login',
    'signUp':'Sign Up',
    'pass':'Password',
    'PhoneNumber': 'Phone Number',
    'email':'Email',
    'confirmnewpassword':'Confirm Password',
    'phonerequired':'phone number is required',
    'passowrdrequired':'Password is required',
    'emailrequired':'Email is required',
    'confirmnewpasswordrequired':'Confirm Password is required',
    'activaccount':'activate the account',
    'confirm':'Confirm',
    'entertheccode':'Enter the code of 6 numbers',
    'whicissent':'That sent to number ',
    'home':'Main',
    'myaccount':'My Account',
    'favorite':'Favorite',
    'shoppingCart':'Shopping Cart',
    'cart':'Cart',
  'settings':'Settings',
    'addtoCart':'add to Cart',
    'description':'Product Description',
    'paymentDetails':'Payment Details',
  'Totalrequests':'Total requests',
    'Totalquantity':'Total quantity',
    'Tax':'Tax',
    'Total':'Total',
    'personaldata':'Personal Profile',
  'name':'name',
  'edit':'Edit',
  'homePage':'home Page',
    'department':'Sections of the store',
    'OrderHistory':'Order History',
  'paymentmethods':'Payment Methods',
  'policy':'Domiciliation and refund policy',
      'lang':'The language',
  'contact_us':'Contact Us',
  'share_app':'Share Application',
  'logout':'Logout',
      'searchfromhere':'search from here',
  'conditions':'all Conditions',
    'sections':'Sections',
    'Offers':'Offers',
      'nofavorite':'There are no favorite items at the moment',
    'shopnow':'shop now',
      'nocartdata':'There are no items in the basket',
      'Doyouwanttodeletetheitem':'Do you want to delete the item?',
    'cancell':'cancell',
    'current':'current',
      'onway':'on way',
      'Delivered':'Delivered',
    'aboutApp':'about App',
    'Totaldemand':'Total demand',
    'Orderstatus':'Order status',
    'nologdata':'There are no items at the moment',
  'username_txt': 'Name',
    'usernamerequired':'name is required',
    'sms':'write your sms',
  'send':'Send',
    'notifications':'notifications',
      'nonotification':'There are no notifications at the moment',
    'Myaddresses':'My addresses',
  'phone':'Phone Number',
      'noaddress':'You haven\'t added addresses yet',
    'addaddress':'add address',
  'followupwiththeorder':'follow up with the order',
  'Continuetopurchase':'Continue to purchase',
    'secondname':'Second Name',
    'DeliveryService':'Delivery Service',
    'Chooseadeliveryservicesystem':'Choose a delivery service system',
    'Deliverywithin':'Delivery within',
    'Chooseadeliverysystem':'Choose a delivery system',
      'operationaccomplishedsuccessfully':'operation accomplished successfully',
    'Viewtheinvoice':'View the bill',
    'Savethebill':'Save the bill',
    'Ordernumber':'Ordernumber',
      'date':'date',
    'details':'details',
  'check':'check',
  'addresstype':'delivery type',
    'loginsms':'You have signed in successfully',
    'enterfullcode':'enter complete code',
    'Theaccounthasbeenactivatedsuccessfully':'The account has been activated successfully',
    'region':'region',
    'city':'City',
    'street':'street',
    'cityrequired':'city is required',
    'regionrequired':'region is required',
    'streetrequired':'street iss required',
    'locationonmap':'The location is on the map',
    'productsusessadd':'added successfly',
 'next':'Next',
  'productsusessremove':'removed successfly',
  'addedbefore':'already in cart',
    'currency':' ج.م ',
    'logedoutsucces':'Logged out successfuly',
    'yes':'Yes',
    'no':'No',
    'logoutdescription':'Do You  want to Logout',
    'more':'more',
    'Modifiedsuccessfully':'Modified successfully',
    'namerequired':'name is required',
    'lost_pass':'Lost Password',
    'changepassword':'Change Password',
    'oldPassword':'Old Password',
    'oldPasswordrequired':'Old Password is required',
    'newpasswordrequired':'New Password is required',
    'confirm_pass':'Confirm Password',
    'confirm_passrequired':'confirm password is required',

    'newPassword':'New Password',
    'savedata':'Save Data',
    'passwordischanged':'تم تغيير كلمة المرور بنجاح',
    'makenote':'write note (option)',
    'Wouldyouliketotellusanythingelse?':'Would you like to tell us anything else?',
    'landmark':'land mark',
    'landmarkrequired':"landmark is required",
    'editdata':'edit data',
    'changpass':'change password',
    'editProfile':'edit Personal Profile',
    'invalideEmail':'Invalid Email',
    'invalidePhone':'Invalid Number',
    'accountiscreated':'تم تفعيل الحساب بنجاح',
    'notmatchd':'كلمة السر غير متطابقة',

    'notavailablenow':'not available now ',
    'delete':'delete',
    'addresstitle':'address title',
    'addresstitlerequired':'address title is required',
    'cancelled':'Cancelled',
    'accepted':'accepted',
  'shipping':'shipped',
  'addtofavorite':'تم الإضافة إلي المفضلة',

  'removetofavorite':'تم الحذف من المفضلة',
  'adddone':'تم الإضافة  بنجاح',
  'addaddressdone':'تمت إضافة العنوان بنجاح',
    'deleteaddress':'تم حذف العنوان بنجاح',
  'choosaddress':'قم باختيار عنوان أولا'



  ,'welcome_txt':'Welcome',
    'welcome_title':'btn_loginWelcome again i our application , we hope you are enjoying',
    'required_filed':'Required Field',
    'lost_password':'Lost Password?',
    'newaccount':'New Account',
    'donthaveaccount':'you do not have an account ?',
    'codewillbesent':'Code will be sent to your phone number',
    'phone_username_email':'Phone , Email , UserName',
    'signupsubscription':'New Subscription',
    'accept':' Accept ',
    'firstname':'First Name',
    'lastname':'Last Name',
    'signning':'Sign ',
    'getpasssowrd':'get password',
    'passwordtext':'يمكنك إستعادة كلمة المرور الخاصة بحسابك الخاص عن تدوين البريد الإلكتروني ثم تفعيل الرابط المرسل ',

    'activation':'Activation',

    'departmentsshopes':'Shopes Departments',

    'myorders':'My Orders',
    'laung':'Laungage',
    'rulesandconditions':'Rules and Conditions',
    'knowus':'Know Us',
    'listaddresses':'List of Adresses',
    'main':'Main',
    'departmentsshops':'Shopes',
    'Featuredproducts':'Featured products',
    'firstdepartment':'First Department',
    'sr':'SR',
    'addtocart':'add to cart',
    'Classificationofstoredepartments':'Classification of store departments',
    'price':'Price',
    'total':'Total',
    'ValueAdded':'Value Added',
    'Discountcoupon':'Discount coupon',
    'Completetheorderprocess':'Complete the order process',
    'Adddiscountcoupon':'Add discount coupon',
    'Youcanaddadiscountcoupon':'You can add a discount coupon',
    'addcoupon':'add Coupon',
    'addDiscountcoupon':'Add Discount coupon',
    'Original':'Original % 100',
    'doyouwanttoshowmore':'Do You Want to Show more about this Product ',
    'clickhere':'Click Here',
    'productcode':'Product Code',
    'reviews':'Reviews',
    'addrating':'Add Your Ratting',
    'qunt':'Quantity',
    'productratting':'Your Comment',
    'addyourcomment':'add your comment',
    'comment':'the comment',
    'save_data':'Add Your Comment ',
    'SavveData':'Save Data',
    'Completethepurchase':'Complete the purchase',
    'Yourrequesthasbeensuccessfullycompleted':'Your request has been successfully completed',
    'Yourordernumber':'Your order number',
    'Thedateofapplication':'The date of application',
    'Yourorderwillarrivewithin':'Your order will arrive within',
    'YoucanfollowyourorderfromtheMyOrderslist':'You can follow your order from the My Orders list',
    'myaddress':'My Address',
    'addnewaddress':'Add new Address',
    'addressName':'Address Name',
    'District':'District',
     'notes':'address notes',
    'editaddres':'Edit Address',
    'deleteaddrees':'Delete Address',
    'Nameofthesavedaddress':'Name of the saved address',
    'workaddress':'work address',
    'addtheaddress':'Add the Addres',
    'message':'Message',
    'requestdetails':'Request Details',
    'caatogeries':'Categoeries',
    'requestnumber':'Request Number',
    'Shippingaddresses':'Shipping addresses',
    'Chooseasavedaddress':'Choose a saved address',
    'addnewadrress':'Add New Address',
    'address':'Address',
    'Paiementwhenrecieving':'Paiement when recieving',
    'Applicationtermination':'Application termination',
    'settinglang':'Settings Language',
    'requiredfield':'Required Field',
    'username':'UserName',
    'acceptallconditions':'you must accept all Terms and Conditions',
    'logedinsucces':'loged in successfly',
    'uncorrectdata':'the entered data is uncorrect',

    'Profileupdatedsuccessfuly':'Profile updated successfuly',
    'thereiserrortryagain':'There is error , try again later',
  'Imageuploadedsuccessfuly':'Image uploaded successfuly',
'nodatafound':'No Data Found'













};
}
